package migration

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

// seedCurrencies seeds the currencies collection with data.
func seedCurrencies(ctx context.Context, db *mongo.Database) error {
	userID, err := primitive.ObjectIDFromHex("66a7b8c9e4b0f12345679000")
	if err != nil {
		return fmt.Errorf("failed to parse userID: %w", err)
	}

	// Create collection if it doesn't exist
	if err := db.CreateCollection(ctx, "currencies"); err != nil {
		if !strings.Contains(err.Error(), "NamespaceExists") {
			return fmt.Errorf("failed to create currencies collection: %w", err)
		}
		log.Println("✅ Currencies collection already exists")
	}

	// Define currency data
	currencies := []bson.M{
		{
			"name":       "US Dollar",
			"short_code": "USD",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Canadian Dollar",
			"short_code": "CAD",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Euro",
			"short_code": "EUR",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "United Arab Emirates Dirham",
			"short_code": "AED",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Afghan Afghani",
			"short_code": "AFN",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Albanian Lek",
			"short_code": "ALL",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Armenian Dram",
			"short_code": "AMD",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Argentine Peso",
			"short_code": "ARS",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Australian Dollar",
			"short_code": "AUD",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Azerbaijani Manat",
			"short_code": "AZN",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Bosnia-Herzegovina Convertible Mark",
			"short_code": "BAM",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Bangladeshi Taka",
			"short_code": "BDT",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Bulgarian Lev",
			"short_code": "BGN",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Bahraini Dinar",
			"short_code": "BHD",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Burundian Franc",
			"short_code": "BIF",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Brunei Dollar",
			"short_code": "BND",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Bolivian Boliviano",
			"short_code": "BOB",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Brazilian Real",
			"short_code": "BRL",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Botswanan Pula",
			"short_code": "BWP",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Belarusian Ruble",
			"short_code": "BYN",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Belize Dollar",
			"short_code": "BZD",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Congolese Franc",
			"short_code": "CDF",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Swiss Franc",
			"short_code": "CHF",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Chilean Peso",
			"short_code": "CLP",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Chinese Yuan",
			"short_code": "CNY",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Colombian Peso",
			"short_code": "COP",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Costa Rican Colón",
			"short_code": "CRC",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Cape Verdean Escudo",
			"short_code": "CVE",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Czech Republic Koruna",
			"short_code": "CZK",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Djiboutian Franc",
			"short_code": "DJF",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Danish Krone",
			"short_code": "DKK",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Dominican Peso",
			"short_code": "DOP",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Algerian Dinar",
			"short_code": "DZD",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Estonian Kroon",
			"short_code": "EEK",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Egyptian Pound",
			"short_code": "EGP",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Eritrean Nakfa",
			"short_code": "ERN",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Ethiopian Birr",
			"short_code": "ETB",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "British Pound Sterling",
			"short_code": "GBP",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Georgian Lari",
			"short_code": "GEL",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Ghanaian Cedi",
			"short_code": "GHS",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Guinean Franc",
			"short_code": "GNF",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Guatemalan Quetzal",
			"short_code": "GTQ",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Hong Kong Dollar",
			"short_code": "HKD",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Honduran Lempira",
			"short_code": "HNL",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Croatian Kuna",
			"short_code": "HRK",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Hungarian Forint",
			"short_code": "HUF",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Indonesian Rupiah",
			"short_code": "IDR",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Israeli New Sheqel",
			"short_code": "ILS",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Indian Rupee",
			"short_code": "INR",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Iraqi Dinar",
			"short_code": "IQD",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Iranian Rial",
			"short_code": "IRR",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Icelandic Króna",
			"short_code": "ISK",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Jamaican Dollar",
			"short_code": "JMD",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Jordanian Dinar",
			"short_code": "JOD",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Japanese Yen",
			"short_code": "JPY",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Kenyan Shilling",
			"short_code": "KES",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Cambodian Riel",
			"short_code": "KHR",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Comorian Franc",
			"short_code": "KMF",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "South Korean Won",
			"short_code": "KRW",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Kuwaiti Dinar",
			"short_code": "KWD",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Kazakhstani Tenge",
			"short_code": "KZT",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Lebanese Pound",
			"short_code": "LBP",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Sri Lankan Rupee",
			"short_code": "LKR",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Lithuanian Litas",
			"short_code": "LTL",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Latvian Lats",
			"short_code": "LVL",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Libyan Dinar",
			"short_code": "LYD",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Moroccan Dirham",
			"short_code": "MAD",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Moldovan Leu",
			"short_code": "MDL",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Malagasy Ariary",
			"short_code": "MGA",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Macedonian Denar",
			"short_code": "MKD",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Myanma Kyat",
			"short_code": "MMK",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Macanese Pataca",
			"short_code": "MOP",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Mauritian Rupee",
			"short_code": "MUR",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Mexican Peso",
			"short_code": "MXN",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Malaysian Ringgit",
			"short_code": "MYR",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Mozambican Metical",
			"short_code": "MZN",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Namibian Dollar",
			"short_code": "NAD",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Nigerian Naira",
			"short_code": "NGN",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Nicaraguan Córdoba",
			"short_code": "NIO",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Norwegian Krone",
			"short_code": "NOK",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Nepalese Rupee",
			"short_code": "NPR",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "New Zealand Dollar",
			"short_code": "NZD",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Omani Rial",
			"short_code": "OMR",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Panamanian Balboa",
			"short_code": "PAB",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Peruvian Nuevo Sol",
			"short_code": "PEN",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Philippine Peso",
			"short_code": "PHP",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Pakistani Rupee",
			"short_code": "PKR",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Polish Zloty",
			"short_code": "PLN",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Paraguayan Guarani",
			"short_code": "PYG",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Qatari Rial",
			"short_code": "QAR",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Romanian Leu",
			"short_code": "RON",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Serbian Dinar",
			"short_code": "RSD",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Russian Ruble",
			"short_code": "RUB",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Rwandan Franc",
			"short_code": "RWF",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Saudi Riyal",
			"short_code": "SAR",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Sudanese Pound",
			"short_code": "SDG",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Swedish Krona",
			"short_code": "SEK",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Singapore Dollar",
			"short_code": "SGD",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Somali Shilling",
			"short_code": "SOS",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Syrian Pound",
			"short_code": "SYP",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Thai Baht",
			"short_code": "THB",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Tunisian Dinar",
			"short_code": "TND",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Tongan Paʻanga",
			"short_code": "TOP",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Turkish Lira",
			"short_code": "TRY",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Trinidad and Tobago Dollar",
			"short_code": "TTD",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "New Taiwan Dollar",
			"short_code": "TWD",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Tanzanian Shilling",
			"short_code": "TZS",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Ukrainian Hryvnia",
			"short_code": "UAH",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Ugandan Shilling",
			"short_code": "UGX",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Uruguayan Peso",
			"short_code": "UYU",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Uzbekistan Som",
			"short_code": "UZS",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Venezuelan Bolívar",
			"short_code": "VEF",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Vietnamese Dong",
			"short_code": "VND",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "CFA Franc BEAC",
			"short_code": "XAF",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "CFA Franc BCEAO",
			"short_code": "XOF",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Yemeni Rial",
			"short_code": "YER",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "South African Rand",
			"short_code": "ZAR",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Zambian Kwacha",
			"short_code": "ZMK",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
		{
			"name":       "Zimbabwean Dollar",
			"short_code": "ZWL",
			"updated_at": time.Now(),
			"created_by": userID,
			"updated_by": nil,
			"deleted_by": nil,
			"deleted_at": nil,
			"is_deleted": false,
			"created_at": time.Now(),
		},
	}

	// Create unique index on short_code to prevent duplicates
	collection := db.Collection("currencies")
	index := mongo.IndexModel{
		Keys:    bson.M{"short_code": 1},
		Options: options.Index().SetUnique(true),
	}
	_, err = collection.Indexes().CreateOne(ctx, index)
	if err != nil {
		return fmt.Errorf("failed to create index on short_code: %w", err)
	}

	// Update or insert currencies
	var updatedCount int64
	for _, currency := range currencies {
		filter := bson.M{"short_code": currency["short_code"]}
		update := bson.M{
			"$set": bson.M{
				"name":       currency["name"],
				"updated_at": currency["updated_at"],
				"updated_by": currency["updated_by"],
				"deleted_by": currency["deleted_by"],
				"deleted_at": currency["deleted_at"],
				"is_deleted": currency["is_deleted"],
			},
			"$setOnInsert": bson.M{
				"short_code": currency["short_code"],
				"created_by": currency["created_by"],
				"created_at": currency["created_at"],
			},
		}
		result, err := collection.UpdateMany(ctx, filter, update, options.Update().SetUpsert(true))
		if err != nil {
			return fmt.Errorf("failed to update currency %s: %w", currency["short_code"], err)
		}
		updatedCount += result.ModifiedCount + result.UpsertedCount
	}

	log.Printf("✅ Updated or inserted %d currencies", updatedCount)
	return nil
}
