package migration

import (
	"context"
	"log"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

func unseedCountries(ctx context.Context, db *mongo.Database) error {
	userID, err := primitive.ObjectIDFromHex("66a7b8c9e4b0f12345679000")
	if err != nil {
		return err
	}

	countries := []interface{}{
		bson.M{"id": 4, "short_code": "afg", "name": "Afganistán", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 248, "short_code": "ala", "name": "Åland", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 8, "short_code": "alb", "name": "Albania", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 276, "short_code": "deu", "name": "Alemania", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 20, "short_code": "and", "name": "Andorra", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 24, "short_code": "ago", "name": "Angola", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 660, "short_code": "aia", "name": "Anguila", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 10, "short_code": "ata", "name": "Antártida", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 28, "short_code": "atg", "name": "Antigua y Barbuda", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 682, "short_code": "sau", "name": "Arabia Saudita", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 12, "short_code": "dza", "name": "Argelia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 32, "short_code": "arg", "name": "Argentina", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 51, "short_code": "arm", "name": "Armenia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 533, "short_code": "abw", "name": "Aruba", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 36, "short_code": "aus", "name": "Australia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 40, "short_code": "aut", "name": "Austria", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 31, "short_code": "aze", "name": "Azerbaiyán", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 44, "short_code": "bhs", "name": "Bahamas", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 50, "short_code": "bgd", "name": "Bangladés", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 52, "short_code": "brb", "name": "Barbados", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 48, "short_code": "bhr", "name": "Baréin", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 56, "short_code": "bel", "name": "Bélgica", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 84, "short_code": "blz", "name": "Belice", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 204, "short_code": "ben", "name": "Benín", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 60, "short_code": "bmu", "name": "Bermudas", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 112, "short_code": "blr", "name": "Bielorrusia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 68, "short_code": "bol", "name": "Bolivia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 535, "short_code": "bes", "name": "Bonaire, San Eustaquio y Saba", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 70, "short_code": "bih", "name": "Bosnia y Herzegovina", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 72, "short_code": "bwa", "name": "Botsuana", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 76, "short_code": "bra", "name": "Brasil", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 96, "short_code": "brn", "name": "Brunéi", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 100, "short_code": "bgr", "name": "Bulgaria", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 854, "short_code": "bfa", "name": "Burkina Faso", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 108, "short_code": "bdi", "name": "Burundi", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 64, "short_code": "btn", "name": "Bután", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 132, "short_code": "cpv", "name": "Cabo Verde", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 116, "short_code": "khm", "name": "Camboya", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 120, "short_code": "cmr", "name": "Camerún", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 124, "short_code": "can", "name": "Canadá", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 634, "short_code": "qat", "name": "Catar", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 148, "short_code": "tcd", "name": "Chad", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 152, "short_code": "chl", "name": "Chile", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 156, "short_code": "chn", "name": "China", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 196, "short_code": "cyp", "name": "Chipre", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 170, "short_code": "col", "name": "Colombia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 174, "short_code": "com", "name": "Comoras", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 408, "short_code": "prk", "name": "Corea del Norte", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 410, "short_code": "kor", "name": "Corea del Sur", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 384, "short_code": "civ", "name": "Costa de Marfil", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 188, "short_code": "cri", "name": "Costa Rica", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 191, "short_code": "hrv", "name": "Croacia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 192, "short_code": "cub", "name": "Cuba", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 531, "short_code": "cuw", "name": "Curazao", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 208, "short_code": "dnk", "name": "Dinamarca", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 212, "short_code": "dma", "name": "Dominica", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 218, "short_code": "ecu", "name": "Ecuador", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 818, "short_code": "egy", "name": "Egipto", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 222, "short_code": "slv", "name": "El Salvador", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 784, "short_code": "are", "name": "Emiratos Árabes Unidos", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 232, "short_code": "eri", "name": "Eritrea", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 703, "short_code": "svk", "name": "Eslovaquia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 705, "short_code": "svn", "name": "Eslovenia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 724, "short_code": "esp", "name": "España", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 840, "short_code": "usa", "name": "Estados Unidos", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 233, "short_code": "est", "name": "Estonia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 231, "short_code": "eth", "name": "Etiopía", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 608, "short_code": "phl", "name": "Filipinas", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 246, "short_code": "fin", "name": "Finlandia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 242, "short_code": "fji", "name": "Fiyi", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 250, "short_code": "fra", "name": "Francia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 266, "short_code": "gab", "name": "Gabón", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 270, "short_code": "gmb", "name": "Gambia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 268, "short_code": "geo", "name": "Georgia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 288, "short_code": "gha", "name": "Ghana", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 292, "short_code": "gib", "name": "Gibraltar", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 308, "short_code": "grd", "name": "Granada", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 300, "short_code": "grc", "name": "Grecia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 304, "short_code": "grl", "name": "Groenlandia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 312, "short_code": "glp", "name": "Guadalupe", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 316, "short_code": "gum", "name": "Guam", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 320, "short_code": "gtm", "name": "Guatemala", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 254, "short_code": "guf", "name": "Guayana Francesa", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 831, "short_code": "ggy", "name": "Guernsey", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 324, "short_code": "gin", "name": "Guinea", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 624, "short_code": "gnb", "name": "Guinea-Bisáu", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 226, "short_code": "gnq", "name": "Guinea Ecuatorial", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 328, "short_code": "guy", "name": "Guyana", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 332, "short_code": "hti", "name": "Haití", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 340, "short_code": "hnd", "name": "Honduras", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 344, "short_code": "hkg", "name": "Hong Kong", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 348, "short_code": "hun", "name": "Hungría", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 356, "short_code": "ind", "name": "India", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 360, "short_code": "idn", "name": "Indonesia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 368, "short_code": "irq", "name": "Irak", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 364, "short_code": "irn", "name": "Irán", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 372, "short_code": "irl", "name": "Irlanda", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 74, "short_code": "bvt", "name": "Isla Bouvet", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 833, "short_code": "imn", "name": "Isla de Man", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 162, "short_code": "cxr", "name": "Isla de Navidad", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 352, "short_code": "isl", "name": "Islandia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 136, "short_code": "cym", "name": "Islas Caimán", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 166, "short_code": "cck", "name": "Islas Cocos", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 184, "short_code": "cok", "name": "Islas Cook", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 234, "short_code": "fro", "name": "Islas Feroe", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 239, "short_code": "sgs", "name": "Islas Georgias del Sur y Sandwich del Sur", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 334, "short_code": "hmd", "name": "Islas Heard y McDonald", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 238, "short_code": "flk", "name": "Islas Malvinas", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 580, "short_code": "mnp", "name": "Islas Marianas del Norte", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 584, "short_code": "mhl", "name": "Islas Marshall", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 612, "short_code": "pcn", "name": "Islas Pitcairn", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 90, "short_code": "slb", "name": "Islas Salomón", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 796, "short_code": "tca", "name": "Islas Turcas y Caicos", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 581, "short_code": "umi", "name": "Islas Ultramarinas Menores de los Estados Unidos", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 92, "short_code": "vgb", "name": "Islas Vírgenes Británicas", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 850, "short_code": "vir", "name": "Islas Vírgenes de los Estados Unidos", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 376, "short_code": "isr", "name": "Israel", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 380, "short_code": "ita", "name": "Italia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 388, "short_code": "jam", "name": "Jamaica", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 392, "short_code": "jpn", "name": "Japón", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 832, "short_code": "jey", "name": "Jersey", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 400, "short_code": "jor", "name": "Jordania", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 398, "short_code": "kaz", "name": "Kazajistán", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 404, "short_code": "ken", "name": "Kenia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 417, "short_code": "kgz", "name": "Kirguistán", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 296, "short_code": "kir", "name": "Kiribati", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 414, "short_code": "kwt", "name": "Kuwait", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 418, "short_code": "lao", "name": "Laos", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 426, "short_code": "lso", "name": "Lesoto", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 428, "short_code": "lva", "name": "Letonia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 422, "short_code": "lbn", "name": "Líbano", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 430, "short_code": "lbr", "name": "Liberia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 434, "short_code": "lby", "name": "Libia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 438, "short_code": "lie", "name": "Liechtenstein", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 440, "short_code": "ltu", "name": "Lituania", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 442, "short_code": "lux", "name": "Luxemburgo", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 446, "short_code": "mac", "name": "Macao", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 807, "short_code": "mkd", "name": "Macedonia del Norte", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 450, "short_code": "mdg", "name": "Madagascar", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 458, "short_code": "mys", "name": "Malasia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 454, "short_code": "mwi", "name": "Malaui", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 462, "short_code": "mdv", "name": "Maldivas", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 466, "short_code": "mli", "name": "Mali", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 470, "short_code": "mlt", "name": "Malta", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 504, "short_code": "mar", "name": "Marruecos", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 474, "short_code": "mtq", "name": "Martinica", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 480, "short_code": "mus", "name": "Mauricio", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 478, "short_code": "mrt", "name": "Mauritania", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 175, "short_code": "myt", "name": "Mayotte", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 484, "short_code": "mex", "name": "México", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 583, "short_code": "fsm", "name": "Micronesia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 498, "short_code": "mda", "name": "Moldavia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 492, "short_code": "mco", "name": "Mónaco", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 496, "short_code": "mng", "name": "Mongolia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 499, "short_code": "mne", "name": "Montenegro", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 500, "short_code": "msr", "name": "Montserrat", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 508, "short_code": "moz", "name": "Mozambique", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 104, "short_code": "mmr", "name": "Birmania", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 516, "short_code": "nam", "name": "Namibia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 520, "short_code": "nru", "name": "Nauru", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 524, "short_code": "npl", "name": "Nepal", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 558, "short_code": "nic", "name": "Nicaragua", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 562, "short_code": "ner", "name": "Níger", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 566, "short_code": "nga", "name": "Nigeria", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 570, "short_code": "niu", "name": "Niue", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 574, "short_code": "nfk", "name": "Isla Norfolk", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 578, "short_code": "nor", "name": "Noruega", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 540, "short_code": "ncl", "name": "Nueva Caledonia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 554, "short_code": "nzl", "name": "Nueva Zelanda", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 512, "short_code": "omn", "name": "Omán", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 528, "short_code": "nld", "name": "Países Bajos", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 586, "short_code": "pak", "name": "Pakistán", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 585, "short_code": "plw", "name": "Palaos", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 275, "short_code": "pse", "name": "Palestina", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 591, "short_code": "pan", "name": "Panamá", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 598, "short_code": "png", "name": "Papúa Nueva Guinea", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 600, "short_code": "pry", "name": "Paraguay", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 604, "short_code": "per", "name": "Perú", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 258, "short_code": "pyf", "name": "Polinesia Francesa", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 616, "short_code": "pol", "name": "Polonia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 620, "short_code": "prt", "name": "Portugal", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 630, "short_code": "pri", "name": "Puerto Rico", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 826, "short_code": "gbr", "name": "Reino Unido", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 732, "short_code": "esh", "name": "República Árabe Saharaui Democrática", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 140, "short_code": "caf", "name": "República Centroafricana", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 203, "short_code": "cze", "name": "República Checa", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 178, "short_code": "cog", "name": "República del Congo", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 180, "short_code": "cod", "name": "República Democrática del Congo", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 214, "short_code": "dom", "name": "República Dominicana", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 638, "short_code": "reu", "name": "Reunión", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 646, "short_code": "rwa", "name": "Ruanda", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 642, "short_code": "rou", "name": "Rumania", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 643, "short_code": "rus", "name": "Rusia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 882, "short_code": "wsm", "name": "Samoa", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 16, "short_code": "asm", "name": "Samoa Americana", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 652, "short_code": "blm", "name": "San Bartolomé", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 659, "short_code": "kna", "name": "San Cristóbal y Nieves", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 674, "short_code": "smr", "name": "San Marino", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 663, "short_code": "maf", "name": "San Martín", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 666, "short_code": "spm", "name": "San Pedro y Miquelón", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 670, "short_code": "vct", "name": "San Vicente y las Granadinas", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 654, "short_code": "shn", "name": "Santa Elena, Ascensión y Tristán de Acuña", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 662, "short_code": "lca", "name": "Santa Lucía", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 678, "short_code": "stp", "name": "Santo Tomé y Príncipe", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 686, "short_code": "sen", "name": "Senegal", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 688, "short_code": "srb", "name": "Serbia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 690, "short_code": "syc", "name": "Seychelles", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 694, "short_code": "sle", "name": "Sierra Leona", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 702, "short_code": "sgp", "name": "Singapur", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 534, "short_code": "sxm", "name": "San Martín", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 760, "short_code": "syr", "name": "Siria", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 706, "short_code": "som", "name": "Somalia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 144, "short_code": "lka", "name": "Sri Lanka", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 748, "short_code": "swz", "name": "Suazilandia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 710, "short_code": "zaf", "name": "Sudáfrica", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 729, "short_code": "sdn", "name": "Sudán", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 728, "short_code": "ssd", "name": "Sudán del Sur", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 752, "short_code": "swe", "name": "Suecia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 756, "short_code": "che", "name": "Suiza", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 740, "short_code": "sur", "name": "Surinam", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 744, "short_code": "sjm", "name": "Svalbard y Jan Mayen", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 764, "short_code": "tha", "name": "Tailandia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 158, "short_code": "twn", "name": "Taiwán (República de China)", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 834, "short_code": "tza", "name": "Tanzania", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 762, "short_code": "tjk", "name": "Tayikistán", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 86, "short_code": "iot", "name": "Territorio Británico del Océano Índico", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 260, "short_code": "atf", "name": "Tierras Australes y Antárticas Francesas", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 626, "short_code": "tls", "name": "Timor Oriental", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 768, "short_code": "tgo", "name": "Togo", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 772, "short_code": "tkl", "name": "Tokelau", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 776, "short_code": "ton", "name": "Tonga", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 780, "short_code": "tto", "name": "Trinidad y Tobago", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 788, "short_code": "tun", "name": "Túnez", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 795, "short_code": "tkm", "name": "Turkmenistán", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 792, "short_code": "tur", "name": "Turquía", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 798, "short_code": "tuv", "name": "Tuvalu", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 804, "short_code": "ukr", "name": "Ucrania", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 800, "short_code": "uga", "name": "Uganda", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 858, "short_code": "ury", "name": "Uruguay", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 860, "short_code": "uzb", "name": "Uzbekistán", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 548, "short_code": "vut", "name": "Vanuatu", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 336, "short_code": "vat", "name": "Vaticano, Ciudad del", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 862, "short_code": "ven", "name": "Venezuela", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 704, "short_code": "vnm", "name": "Vietnam", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 876, "short_code": "wlf", "name": "Wallis y Futuna", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 887, "short_code": "yem", "name": "Yemen", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 262, "short_code": "dji", "name": "Yibuti", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 894, "short_code": "zmb", "name": "Zambia", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
		bson.M{"id": 716, "short_code": "zwe", "name": "Zimbabue", "visa_status": false, "created_at": time.Now(), "updated_at": time.Now(), "created_by": userID, "deleted_by": nil, "deleted_at": nil, "is_deleted": false},
	}

	var deleteModels []mongo.WriteModel
	for _, c := range countries {
		country := c.(bson.M)

		model := mongo.NewDeleteOneModel().
			SetFilter(bson.M{"id": country["id"]})

		deleteModels = append(deleteModels, model)
	}

	opts := options.BulkWrite().SetOrdered(false)
	_, err = db.Collection("countries").BulkWrite(ctx, deleteModels, opts)
	if err != nil {
		log.Fatal("Error during unseeding countries:", err)
	}

	return err
}
